void Py_Initialize ()
void Py_Finalize ()
PyObject* PyDict_New ()
PyObject* PyLong_FromLongLong (longlong)
PyObject* PyFloat_FromDouble (double)
PyObject* PyDict_Copy (PyObject*)
PyObject* PyEval_GetBuiltins ()
PyObject* PyEval_EvalCode (PyObject* PyObject* PyObject*)
double PyFloat_AsDouble (PyObject*)
longlong PyLong_AsLongLong (PyObject*)
PyObject* Py_CompileString (char* char* int)
int PyDict_SetItemString (PyObject* char* PyObject*)
